config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  get 'topics/new'
  get 'sessions/new'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resource :user
  resources :topics do
    resources :comments
    post '/favorites', to: 'favorites#create'
    delete '/favorites', to: 'favorites#destroy'
  end
  
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'favorites/index'
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id          :bigint           not null, primary key
#  user_id     :integer
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string(255)
#
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: "user"
  has_many :comments
  has_many :comment_users, through: :comments, source: "user"

  mount_uploader :image, ImageUploader
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @user = current_user
    @type = params[:type]

    if @type == "user"
      @topics = current_user.topics

    elsif @type == "favorite"
      # もし type が「favorite」だったら
      # @topics にログイン中ユーザがお気に入りしているトピックに絞り込んだものを入れる。
      @topics = current_user.favorite_topics

    elsif @type == "comment"
      # もし type が「commented」だったら
      # @topics にログイン中ユーザがコメントしたトピックに絞り込んだものを入れる。
      @topics = current_user.comment_topics.distinct

    else
      # もし type が上のどれでもなかったら
      # @topics はそのまま。
      @topics = Topic.eager_load(:user)
    end

    @topics = @topics.order(created_at: :desc)
  end

  def show
    @topic = Topic.find(params[:id])
    @user = @topic.user
    @comments = @topic.comments
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: '投稿しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def destroy
    @topic = current_user.topics.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  private

  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <ul class="user-tabs">
    <li class="<%= 'active' if @type != "user" &&  @type != "favorite" && @type != "comment" %>"><%= link_to '投稿一覧', topics_path %></li>
    <li class="<%= 'active' if @type == "user" %>"><%= link_to ("自分の投稿"), topics_path(type: :user) %></li>
    <li class="<%= 'active' if @type == "favorite" %>"><%= link_to 'お気に入り', topics_path(type: :favorite) %></li>
    <li class="<%= 'active' if @type == "comment" %>"><%= link_to 'コメントした投稿', topics_path(type: :comment) %></li>
  </ul>
  <div class="container">
    <h1 class="topic-list">
      <%= "投稿一覧" if @type != "user" &&  @type != "favorite" && @type != "comment" %>
      <%= "自分の投稿" if @type == "user" %>
      <%= "お気に入り" if @type == "favorite" %>
      <%= "コメントした投稿" if @type == "comment" %>
    </h1>

    <% @topics.each do |topic| %>
      <div class="topic-row">
        <div class="topic-index-single">
          <h2 class="topic-author">
            <%= topic.user.name %>
          </h2>
          <p class="topic-time">
            <%= I18n.l(topic.created_at, format: :long) %>
          </p>
          <%= image_tag topic.image.url %>

          <p class="topic-text">
            <%= simple_format(topic.description) %>
          </p>

          <% if !topic.favorite_users.include?(current_user) %>
            <%= link_to topic_favorites_path(topic_id: topic.id), method: :post do %>
              <i class="fa fa-heart like-btn topic-index-icon fa-2x"></i>
            <% end %>
          <% else %>
            <%= link_to topic_favorites_path(topic_id: topic.id), method: :delete do %>
              <i class="fa fa-heart unlike-btn topic-index-icon fa-2x"></i>
            <% end %>
          <% end %>
          <%= topic.favorite_users.count %>

          <%= link_to topic_path(topic) do%>
            <i class="far fa-comment topic-index-icon fa-2x"></i>
          <% end %>
          <%= topic.comment_users.count %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="topic-new">
      <h1 class="text-center">投稿する</h1>
      <%= form_for @topic do |f| %>
        <div class="new-form">
          <div class="form-group">
            <%= f.file_field :image%>
          </div>
      
          <% @topic.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
      
          <div class="form-group">
            <%= f.text_area :description, :size => "60x10", class: 'form-control' %>
          </div>
        </div>
        <% if logged_in? %>
          <div class="form-button">
            <%= f.submit '投稿', class: 'new-block' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <h1 class="topic-list">コメント一覧</h1>
    <div class="topic-row">
      <div class="topic-index-single">
        <h2 class="topic-author">
          <%= @topic.user.name %>
        </h2>
        <p class="topic-time">
          <%= I18n.l(@topic.created_at, format: :long) %>
        </p>
        <%= image_tag @topic.image.url %>
        
        <p class="topic-text">
          <%= simple_format(@topic.description) %>
        </p>
        <div class="cf">
          <div class="topic-comment">
            <i class="far fa-comment topic-comment-icon fa-2x"></i>
            <%= link_to 'コメントする', new_topic_comment_path(@topic), class: 'user-comment' %>
          </div>
        </div>
        <div class="content">
          <% @comments.each do |comment| %>
            <div class="comment-text">
              <h3 class="comment-name"><%= comment.user.name %><br></h3>
              <div class="post-menus">
                <% if current_user.id == comment.user_id %>
                  <%= link_to '削除', topic_comment_path(@topic, comment.id), method: :delete %>
                <% end %>
              </div>
              <ul>
                <li>
                  <%= simple_format(comment.content) %><br>
                  <span><%= I18n.l(comment.created_at, format: :long) %></span>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>