config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  get 'topics/new'
  get 'sessions/new'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resource :user
  resources :topics do
    resources :comments
    post '/favorites', to: 'favorites#create'
    delete '/favorites', to: 'favorites#destroy'
  end
  
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'favorites/index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  image_name      :string(255)
#  sex             :string(255)
#  nickname        :string(255)
#  birth_date      :date
#
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i

  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true,  format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, on: :create, format: { with: VALID_PASSWORD_REGEX }
  validates :nickname, length: { maximum: 50 }

  has_secure_password

  mount_uploader :image_name, ImageUploader

  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: "topic"
  has_many :comments
  has_many :comment_topics, through: :comments, source: "topic"
  has_many :events
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @topics = @user.topics.order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(update_params)
      redirect_to user_path, success: 'ユーザー情報を編集しました。'
    else
      flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation) #:image, :nickname, :sex, :age
  end

  def update_params
    params.require(:user).permit(:name, :email, :image_name, :nickname, :sex, :birth_date)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="users-edit-wrapper">
  <div class="container">
    <div class="users-edit-container">
      <h1 class="text-center">プロフィール編集</h1>

      <%= form_for @user, url: user_path do |f| %>
        <div class="form-group">
          <%= f.label :image_name, 'image' %>
          <%= f.file_field :image_name %>
        </div>
        <div class="form-group">
          <%= f.label :name, class: 'text-white' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, class: 'text-white' %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :nickname, class: 'text-white' %>
          <%= f.text_field :nickname, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :birth_date, class: 'text-white' %>
          <%= f.date_field :birth_date, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :sex, class: 'text-white' %>
          <%= f.text_field :sex, class: 'form-control' %>
        </div>

        <div class="form-group">
        <%= f.submit "編集を完了する", class: 'new-block' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<body>

  <div class="users-new-wrapper">
    <div class="container">
      <div class="row">
        <div class="users-new-container">
          <h1 class="text-center">新規登録</h1>
          <% @user.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>
          <%= form_for @user, url: user_path do |f| %>
            <div class="form-group">
              <%= f.label :name, class: 'text-white' %>
              <%= f.text_field :name, placeholder: "15文字まで", class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :email, class: 'text-white' %>
              <%= f.text_field :email, placeholder: "***@**.**", class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password, class: 'text-white' %>
              <%= f.password_field :password, placeholder: "半角英数字含めた、8~32文字", class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation, class: 'text-white' %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.submit "登録", class: 'new-block' %>
          <% end %>
            <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
            </div>
        </div>
      </div>
    </div>
  </div>

</body>

app/views/users/show.html.erb
<div class="user-show">
  <div class="container">
    <div class="user">
      <div class="cf">
        <div class="user-image">
          <% if @user.image_name? %>
            <%= image_tag  @user.image_name.url, :class => "mw50" %>
          <% else %>
            <%= image_tag "82214.jpg" %>
          <% end %>
        </div>

        <div class="user-informations">
          <div  class="user-group">
            <h3>お名前</h3><br>
            <p><%= @user.name %></p>
          </div>
          <div  class="user-group">
            <h3>メールアドレス</h3>
            <p><%= @user.email %></p>
          </div>
          <div  class="user-group">
            <h3>愛犬のお名前</h3>
            <p><%= @user.nickname %></p>
          </div>
          <div  class="user-group">
            <h3>愛犬のお誕生日</h3>
            <p><%= @user.birth_date %></p>
          </div>
          <div  class="user-group">
            <h3>愛犬の性別</h3>
            <p><%= @user.sex %></p>
          </div>

          <%= link_to '編集する', edit_user_path(current_user.id), class: 'user-white' %>
        </div>
      </div>
    </div>

    <h1 class="user-list">自分の投稿</h1>
    <% @topics.each do |topic| %>
      <div class="user-topic-single">
        <h2 class="topic-author">
          <%= topic.user.name %>
        </h2>
        <p class="topic-time">
          <%= I18n.l(topic.created_at, format: :long) %>
        </p>
        <%= image_tag topic.image.url %>

        <p class="topic-text">
          <%= simple_format(topic.description) %>
        </p>
        <% if !topic.favorite_users.include?(current_user) %>
          <%= link_to topic_favorites_path(topic_id: topic.id), method: :post do %>
            <i class="fa fa-heart like-btn topic-index-icon fa-2x"></i>
          <% end %>
        <% else %>
          <%= link_to topic_favorites_path(topic_id: topic.id), method: :delete do %>
            <i class="fa fa-heart unlike-btn topic-index-icon fa-2x"></i>
          <% end %>
        <% end %>
        <%= topic.favorite_users.count %>

        <%= link_to topic_path(topic) do%>
          <i class="far fa-comment topic-index-icon fa-2x"></i>
        <% end %>
        <%= topic.comment_users.count %>

        <div class="post-menus">
          <%= link_to '投稿削除', topic_path(topic), method: :delete  %>
        </div>
      </div>
    <% end %>
  </div>
</div>