config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  get 'topics/new'
  get 'sessions/new'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resource :user
  resources :topics do
    resources :comments
    post '/favorites', to: 'favorites#create'
    delete '/favorites', to: 'favorites#destroy'
  end
  
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'favorites/index'
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="form-error">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li> 
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogCareBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert" ><%= value %></div>
    <% end %>

  <header>
    <div class="header-logo">
      <%= link_to root_path do %>
        Dog Care Book
      <% end %>
    </div>

    <div class="menu-btn">
      <span class="fa fa-bars menu-icon"></span>
      <ul class="menu">
        <% if logged_in? %>
          <li class="<%= navigation_item_class("events") %>">
            <%= link_to 'カレンダー', events_path, class: 'menu__item' %>
          </li>
          <li class="<%= navigation_item_class("topics", except: "new") %>">
            <%= link_to '投稿一覧', topics_path, class: 'menu__item' %>
          </li>
          <li class="<%= navigation_item_class("topics", "new") %>">
            <%= link_to '新規投稿', new_topic_path, class: 'menu__item' %>
          </li>
          <li class="<%= navigation_item_class("users") %>">
            <%= link_to 'マイページ', user_path(current_user.id), class: 'menu__item' %>
          </li>
          <li>
            <%= link_to 'ログアウト', logout_path, method: :delete %>
          </li>
        <% else %>
          <li class="<%= navigation_item_class("users", "new") %>">
            <%= link_to '新規登録', new_user_path, class: 'menu__item' %>
          </li>
          <li class="<%= navigation_item_class("sessions", "new") %>">
            <%= link_to 'ログイン', login_path, class: 'menu__item' %>
          </li>
        <% end %>
      </ul>
      </div>

      <ul class="header-menus">
        <% if logged_in? %>
          <li class="<%= navigation_item_class("events") %>">
            <%= link_to 'カレンダー', events_path, class: 'btn-block' %>
          </li>
          <li class="<%= navigation_item_class("topics", except: "new") %>">
            <%= link_to '投稿一覧', topics_path, class: 'btn-block' %>
          </li>
          <li class="<%= navigation_item_class("topics", "new") %>">
            <%= link_to '新規投稿', new_topic_path, class: 'btn-block' %>
          </li>
          <li class="<%= navigation_item_class("users") %>">
            <%= link_to 'マイページ', user_path(current_user.id), class: 'btn-block' %>
          </li>
          <li>
            <%= link_to 'ログアウト', logout_path, method: :delete %>
          </li>
        <% else %>
          <li class="<%= navigation_item_class("users", "new") %>">
            <%= link_to '新規登録', new_user_path, class: 'btn-block' %>
          </li>
          <li class="<%= navigation_item_class("sessions", "new") %>">
            <%= link_to 'ログイン', login_path, class: 'btn-block' %>
          </li>
        <% end %>
      </ul>
  </header>

    <!-- カレンダー追加分 -->
    <body data-turbolinks="false">
    <%= yield %>
    </body>

    <script>
  $(function(){
    $(".alert").fadeOut(5000);
  });

$(function(){
  $('.menu-btn').on('click', function(){
    $('.menu').toggleClass('is-active');
  });
}());
</script>

  </body>
</html>